export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';
export const ADD_CATEGORY_STARTED = 'ADD_CATEGORY_STARTED';

export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_FAILURE = 'EDIT_CATEGORY_FAILURE';
export const EDIT_CATEGORY_STARTED = 'EDIT_CATEGORY_STARTED';

export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';
export const DELETE_CATEGORY_STARTED = 'DELETE_CATEGORY_STARTED';

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';
export const GET_CATEGORIES_STARTED = 'GET_CATEGORIES_STARTED';


export const ADD_TOPIC_SUCCESS = 'ADD_TOPIC_SUCCESS';
export const ADD_TOPIC_FAILURE = 'ADD_TOPIC_FAILURE';
export const ADD_TOPIC_STARTED = 'ADD_TOPIC_STARTED';

export const EDIT_TOPIC_SUCCESS = 'EDIT_TOPIC_SUCCESS';
export const EDIT_TOPIC_FAILURE = 'EDIT_TOPIC_FAILURE';
export const EDIT_TOPIC_STARTED = 'EDIT_TOPIC_STARTED';

export const DELETE_TOPIC_SUCCESS = 'DELETE_TOPIC_SUCCESS';
export const DELETE_TOPIC_FAILURE = 'DELETE_TOPIC_FAILURE';
export const DELETE_TOPIC_STARTED = 'DELETE_TOPIC_STARTED';

export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const GET_TOPICS_STARTED = 'GET_TOPICS_STARTED';



export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_FAILURE = 'ADD_QUESTION_FAILURE';
export const ADD_QUESTION_STARTED = 'ADD_QUESTION_STARTED';

export const EDIT_QUESTION_SUCCESS = 'EDIT_QUESTION_SUCCESS';
export const EDIT_QUESTION_FAILURE = 'EDIT_QUESTION_FAILURE';
export const EDIT_QUESTION_STARTED = 'EDIT_QUESTION_STARTED';

export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_FAILURE = 'DELETE_QUESTION_FAILURE';
export const DELETE_QUESTION_STARTED = 'DELETE_QUESTION_STARTED';

export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAILURE = 'GET_QUESTIONS_FAILURE';
export const GET_QUESTIONS_STARTED = 'GET_QUESTIONS_STARTED';


